version: '3.8'
services:
  mqtt:
    image: mqtt-broker:latest
    container_name: mqtt-broker
    build:
      context: ./mqtt/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "15672:15672"
  mongodb:
    image: mongo:latest
    container_name: mongodb-c
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  web-api:
    image: net-api:latest
    container_name: api-container
    build:
      context: ./backend/IoTApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
      - mqtt



