# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Set a custom data directory (optional)
# ENV MONGO_DATA_DIR=/data/db

# Expose the default MongoDB port
EXPOSE 27017

# Start the MongoDB server
CMD ["mongod"]
